"""session format_overrides

Revision ID: 7ec56b135b83
Revises: fe86623f380c
Create Date: 2026-08-16 20:59:46.829148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec56b135b83'
down_revision = 'fe86623f380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_overrides', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('format_overrides')

    # ### end Alembic commands ###
