"""initial schema

Revision ID: fe86623f380c
Revises: 
Create Date: 2026-08-16 19:25:10.464369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe86623f380c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('profile_key', sa.String(length=40), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('expected_hr_min', sa.Integer(), nullable=True),
    sa.Column('expected_hr_max', sa.Integer(), nullable=True),
    sa.Column('comparison_key', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_type_profile_key'), ['profile_key'], unique=False)

    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('athlete_baseline', sa.Boolean(), nullable=False),
    sa.Column('max_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_slug'), ['slug'], unique=True)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('sampling_rate_hz', sa.Float(), nullable=True),
    sa.Column('context_note', sa.String(length=2000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('engine_used', sa.String(length=40), nullable=True),
    sa.Column('ecg_unit_detected', sa.String(length=8), nullable=True),
    sa.Column('epoch_detected', sa.String(length=16), nullable=True),
    sa.Column('beats_corrected_pct', sa.Float(), nullable=True),
    sa.Column('reduced_confidence', sa.Boolean(), nullable=False),
    sa.Column('excluded_s', sa.Float(), nullable=True),
    sa.Column('analysed_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("processing_status IN ('pending', 'running', 'needs_mapping', 'done', 'error')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256', name='uq_session_file_sha256')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_activity_type_id'), ['activity_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_person_id'), ['person_id'], unique=False)

    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_person_id'), ['person_id'], unique=False)

    op.create_table('excluded_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excluded_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_segment_session_id'), ['session_id'], unique=False)

    op.create_table('flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(disclaimer)) > 0', name='ck_flag_disclaimer_nonempty'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flag_session_id'), ['session_id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('n_beats', sa.Integer(), nullable=True),
    sa.Column('mean_rr_ms', sa.Float(), nullable=True),
    sa.Column('mean_hr_bpm', sa.Float(), nullable=True),
    sa.Column('sdnn_ms', sa.Float(), nullable=True),
    sa.Column('rmssd_ms', sa.Float(), nullable=True),
    sa.Column('pnn50_pct', sa.Float(), nullable=True),
    sa.Column('vlf_power_ms2', sa.Float(), nullable=True),
    sa.Column('lf_power_ms2', sa.Float(), nullable=True),
    sa.Column('hf_power_ms2', sa.Float(), nullable=True),
    sa.Column('lf_hf_ratio', sa.Float(), nullable=True),
    sa.Column('sd1_ms', sa.Float(), nullable=True),
    sa.Column('sd2_ms', sa.Float(), nullable=True),
    sa.Column('sd1_sd2_ratio', sa.Float(), nullable=True),
    sa.Column('sample_entropy', sa.Float(), nullable=True),
    sa.Column('dfa_alpha1', sa.Float(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_session_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flag_session_id'))

    op.drop_table('flag')
    with op.batch_alter_table('excluded_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_segment_session_id'))

    op.drop_table('excluded_segment')
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_person_id'))

    op.drop_table('annotation')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_person_id'))
        batch_op.drop_index(batch_op.f('ix_session_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_session_activity_type_id'))

    op.drop_table('session')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_slug'))

    op.drop_table('person')
    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_type_profile_key'))

    op.drop_table('activity_type')
    # ### end Alembic commands ###
